name: CD - Deploy to EC2

on:
  workflow_run:
    workflows:
      - CI - Build & Push Docker Image
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy container
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            IMAGE_TAG=${{ github.event.workflow_run.head_sha }}

            sudo docker pull gioleonp/empre-backend:$IMAGE_TAG

            sudo docker stop empre-back || true
            sudo docker rm empre-back || true

            sudo docker run -d \
              --name empre-back \
              -p 8080:8080 \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e S3_BUCKET=${{ secrets.S3_BUCKET }} \
              -e S3_REGION=${{ secrets.S3_REGION }} \
              -e APP_URL=${{ secrets.APP_URL }} \
              gioleonp/empre-backend:$IMAGE_TAG
          EOF
